### PR TITLE
Better message to eclipse

### PR DESCRIPTION
**Pull request by leocwolter**

### CODE REVIEW

**Comment by garcia-jj** [comment]
:-1: for this change. Error messages should generic for all cases, not for one IDE only. This kind of message can be added to readme or project docs, not inside the code.

**Comment by Turini** [comment]
No need to :-1: , but I agree that we shouldn't add so specific message. 
If it's not present at plugin docs, we can add or improve the warning for users.

**Comment by leocwolter** [comment]
I can change it to be at our README then :)

**Comment by garcia-jj** [comment]
Readme ++. And we can improve with more IDEs in the future.

**Comment by leocwolter** [comment]
Already done :)

**Comment by Turini** [comment]
thanks @leocwolter!

**Pull request merged**
